### ISSUE TITLE
convert fasta to aln generation

### ISSUE THREAD

**Issue by sathyapatel** [badriadhikari/IEEE-ICMLA-2019-PIDP-Challenge#3]
Hi,
I am trying to generate aln files for each fasta files has given here. Can you refer any script or tool to convert fasta file to aln file?, I tried other tools like FASCONVERT generates .aln but, SCRATCH causes invalid protein sequence sometimes and  length alignment mismatch during free contact predictions and ccmpred. 

does metapsicov generate aln file ? Kindly share it to sathyapatel@gmail.com

**Comment by badriadhikari** [comment]
Hi Sathya,

To generate aln files you will need to use HHsearch or JackHmmer. Here is
an example:
https://github.com/multicom-toolbox/DNCON2/blob/master/scripts/jack_hhblits.pl

- Badri

**Comment by sathyapatel** [comment]
Hi, 
I mentioned database as uniref100 in runmetapsicov.pl and esl-sfetch to create uniref100 SSI index which generates aln, freecontact predictions.. I am able to create  protein_name.input.feature file.
It's working now. Thanks!!
